version: '2'

services:
  db57:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_USER=docker
      - MYSQL_DATABASE=dev
    ports:
      - "3306:3306"
