default: &default
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: tst

production:
  <<: *default
  database: prd
