name: TDD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: docker
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Mysql Client
      run: |
        sudo apt-get install -y mysql-client libmysqlclient-dev
    - name: Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Build App
      env:
        DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}
        DATABASE_PASSWORD: docker
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle
        bin/rails db:setup
    - name: Run Tests
      env:
        DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}
        DATABASE_PASSWORD: docker
        RAILS_ENV: test
      run: |
        bundle exec rspec
